site_name: Mera_Portfolio
site_url: https://tosif7727.github.io/portfolio/
use_directory_urls: false

# Navigation structure
nav:
   - Home: index.md
   - Skill: skill.md
   - Blog:
      - Blog_1: blog/blog_1.md
      
   - Assignments:
      - Assignment_1: assignments/assignments_1.md

   - Contact: contact.md
   
        
  

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
